#!/usr/bin/env python  
# -*- coding:utf-8 -*-

def print_error(msg):
	print "\033[1;31m"+msg+"\033[0m"

def print_normal(msg):
	print "\033[1;34m"+msg+"\033[0m"

from selenium import webdriver
from pyvirtualdisplay import Display

from bs4 import BeautifulSoup

def download_special(problem_id):
	display = Display(visible=0, size=(800, 600))
	display.start()

	browser = webdriver.Firefox()
	browser.get('http://www.lydsy.com/JudgeOnline/loginpage.php')
	username = browser.find_element_by_xpath("//input[@name='user_id']")
	username.clear()
	username.send_keys("zhangche0526")
	password = browser.find_element_by_xpath("//input[@name='password']")
	password.clear()
	password.send_keys("Glees6Actangyut")
	browser.find_element_by_xpath("//input[@name='submit']").click()
	url = "http://www.lydsy.com/JudgeOnline/problem.php?id=" + str(problem_id)
	browser.get(url)
	soup = BeautifulSoup(browser.page_source,"html.parser")
	del display
	del browser
	return soup

import requests
def download_general(problem_id):
	url = "http://www.lydsy.com/JudgeOnline/problem.php?id=" + str(problem_id)
	response=requests.get(url)
	soup = BeautifulSoup(response.text.encode(response.encoding).decode('utf8'),"html.parser")
	return soup

def craw(problem_id):
	soup=download_general(problem_id)
	if soup.find(class_='sampledata')==None:#Error Exception should be added here
		soup=download_special(problem_id)
	return soup

def submit_solution(problem_id, source_code):
	display = Display(visible=0, size=(800, 600))
	display.start()

	browser = webdriver.Firefox()
	browser.get('http://www.lydsy.com/JudgeOnline/problem.php?id='+problem_id)
	exec_js = 'document.getElementById("frame_source").contentWindow.document.body.innerHTML="%s"' %(source_code)
	browser.execute_script(exec_js)

	browser.find_element_by_xpath("//input[@value='Submit']").click()
	url = "http://www.lydsy.com/JudgeOnline/status.php?user_id=zhangche0526"
	browser.get(url)
	soup = BeautifulSoup(browser.page_source,"html.parser")

def parse_judge_result(problem_id, soup):
	status_row = soup.find(class_='evenrow')
	result_list = ['']
	result_list[0] = craw(problem_id).h2.string
	result_list[1] = status_row.children[3].children[0].string
	result_list[2] = status_row.children[4].string + "kB"
	result_list[3] = status_row.children[5].string + "ms"
	return status_row, result_list

def online_judge(problem_id, source_code):
    status_row, result_list     

def parse_sample(soup):
	problem_title=soup.h2.string
	sample_input=''
	sample_output=''
	cnt=0
	for sample_data in soup.find_all(class_='sampledata'):
		for row in sample_data.children:
			if row.string!=None:
				if cnt==0:
					sample_input=sample_input+row.string
				else:
					sample_output=sample_output+row.string
		cnt=cnt+1
	return problem_title, sample_input, sample_output

import os
def check_sample(problem_id, source_file_name = None):
	if source_file_name == None:
		source_file_name = problem_id+".cpp"
	print "Getting Sample..."
	problem_title, sample_input, sample_output = parse_sample(craw(problem_id))
	input_file=open("data.in",'w')
	input_file.write(sample_input)
	input_file.close()
	output_file=open("data.out",'w')
	output_file.write(sample_output)
	output_file.close()
	exec_file_name=problem_id+".exec"
	print "Compiling..."
	complie_result = os.system("g++ "+source_file_name+" -o "+exec_file_name+" -O2 -Wall")
	if(complie_result != 0):
		print "\033[1;31m"+"CE"+"\033[0m"
		return
	print "Running..."
	run_result = os.system("./"+exec_file_name+" < data.in > user.out")
	if(run_result != 0):
		print "\033[1;31m"+"RE"+"\033[0m"
		return
	diff_result = os.system("diff -bB user.out data.out")
	if(diff_result == 0):
		print_normal("Good! Your programe has just passed the sample.");
	else:
		print_error(diff_result)
	os.remove("data.in")
	os.remove("data.out")
	os.remove("user.out")
	os.remove(exec_file_name)
	
def print_help_msg():
	print "Usage:"
	print "\"-h\": Show this."

import sys, getopt
reload(sys) 
sys.setdefaultencoding('utf-8') 

opts, args = getopt.getopt(sys.argv[1:],"hc::")
for opt, val in opts:
	if opt == "-h":
		print_help_msg()
	if opt == "-c":
		if len(args) == 0:
			check_sample(val)
		else:
			check_sample(val, args[0])
